[package]
name = "my-project"
version = "0.1.0"
edition = "2021"
authors = ["John Turner <jturner@b1tsized.tech>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
